### PR TITLE
Rgb colormap

### PR DESCRIPTION
**Pull request by ziyangczi**
Hi there, my name is Ziyang and I am trying to help you with your first PR to napari! Thank you for your contribution and I am happy to explain some of my proposed changes on top of your commits.

so the first thing I changed is how the RGB flag is fetched, as you may have already noticed, some tests failed because other layers than the image layer did not have RGB flags set already, so I am checking if it exists first before using its value, so the behavior would be consistent as before (assuming RGB is false if the flag is not present). I think you may have been trying to add RGB support for the surface layer, if so we need to have another PR to add that.

the second thing is how the invisible flag is set, notice that qt element would be visible once they are initialized, that's why you are seeing the ghost menu at the top left corner. This is because when the reference is removed to put them in a box, they are defaulted to be displayed on the top left corner.

the third thing is that I reversed the change on the surface layer, I think this was unintended when you try to make the changes.

Let me know what you think, I hope this helps to unblock your PR progress.

ps. sorry about the massive change list, if you pull from the master branch from napari repo you should see most of it gone.

### CODE REVIEW

**Comment by ziyangczi** [comment]
@ekdnam do you mind merging this to your branch and give it a try? I can open another PR from my branch to the main repo if you wish

**Comment by ekdnam** [comment]
Hey @ziyangczi . Sorry for not responding. I have been a bit busy with college related stuff. I am going to look into that during the weekend. Would that be okay?

**Comment by ziyangczi** [comment]
> Hey @ziyangczi . Sorry for not responding. I have been a bit busy with college related stuff. I am going to look into that during the weekend. Would that be okay?

yeah totally! thanks for checking!

**Comment by ekdnam** [comment]
Most importantly, I want to look into what changes you have made and learn, since you have made some quite extensive changes and have spent a lot of time on them, rather than just glossing over them. So, I am waiting for when my college stuff will get over. Hoping you will understand! 😀

**Pull request merged**
